version: '3'

services:
  markr-production:
    build:
      context: .
      target: production
    image: markr
    container_name: markr
    environment:
      - NODE_ENV=production
      - PORT=4567
    ports:
      - '4567:4567'
    volumes:
      - ./database:/usr/node/markr/database
      - ./rejected:/usr/node/markr/rejected
      - node_modules:/usr/node/markr/node_modules

volumes:
  node_modules:
