version: '3'

services:
  markr-dev:
    build:
      context: .
      target: development
    image: markr-dev
    container_name: markr-dev
    environment:
      - NODE_ENV=development
      - PORT=4567
    ports:
      - '4567:4567'
    volumes:
      - .:/usr/node/markr
      - node_modules:/usr/node/markr/node_modules

volumes:
  node_modules:
